version: 2
jobs:
  build:
    docker:
      - image: v2tec/gobuilder:0.2.0_go1.7.4-glide0.12.3-goreleaser0.40.3-docker17.03.0
    working_directory: /src
    steps:
      - checkout
      - setup_remote_docker:
          version: 17.03.0-ce
      - run: git fetch --tags
      - run: |
          IS_RELEASE=$(if [ "$CIRCLE_TAG" != "" ] ; then echo release; else echo ci; fi;)
          /build.sh $IS_RELEASE

      - store_artifacts:
          path: /src/dist/
workflows:
  version: 2
  build-deploy:
    jobs:
      - build:
          filters:
            tags:
              only: /.*/